routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::resource('links', 'LinksController');

    Route::get('{code}', 'LinksController@go')->name('links.go');
});

app/Link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $fillable = [
        'id',
        'name',
        'url'
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }


    public function getLinkAttribute()
    {
        return route('links.go', $this->code);
    }


    // Scopes
    public function scopeCode($query, $code)
    {
        return $query->where('code', $code);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function links()
    {
        return $this->hasMany('App\Link');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LinksController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\LinkFactoryContract;
use App\Contracts\LinksRepositoryContract;
use App\Link;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class LinksController extends Controller
{
    /**
     * @var LinksRepositoryContract
     */
    public $links;

    /**
     * @var LinkFactoryContract
     */
    public $factory;

    public function __construct(LinksRepositoryContract $links, LinkFactoryContract $factory)
    {
        $this->links = $links;
        $this->factory = $factory;
    }

    /**
     * View all user's links.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $links = $this->links->getAllByUser(auth()->user());

        return view('links.index', compact('links'));
    }

    /**
     * Create form for new link.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('links.create');
    }

    /**
     * Create a new link.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'url' => 'required|url',
            'name' => 'required'
        ]);

        $this->factory->make(auth()->user(), $request->all());

        session()->flash('message', 'Link added.');

        return redirect()->route('links.index');
    }

    /**
     * Delete a link.
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $link = $this->links->find($id);
        $link->delete();

        session()->flash('message', 'Link deleted.');

        return redirect()->route('links.index');
    }

    /**
     * Move to the url.
     *
     * @param $code
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function go($code)
    {
        $link = $this->links->getByCode($code);
        DB::table('links')->where('id', $link->id)->increment('views');

        return redirect($link->url);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('links.index') }}">
                                Links
                            </a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @if (session()->has('message'))
                <div class="container">
                    <div class="alert alert-success">
                        {{ session('message') }}
                    </div>
                </div>
            @endif

            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/links/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-body">
                <form action="{{ route('links.store') }}" method="post">
                    @csrf

                    @include('links.form', ['link' => new App\Link])

                    <button type="submit" class="btn btn-primary">
                        Create
                    </button>

                    <a href="{{ route('links.index') }}" class="btn btn-outline-secondary">
                        Cancel
                    </a>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/links/form.blade.php
<div class="form-group">
    <label for="name">Name</label>
    <input type="text" id="name" name="name" class="form-control" value="{{ old('name', $link->name) }}" required>
    @if ($errors->has('name'))
        <small class="form-text text-muted">
            {{ $errors->first('name') }}
        </small>
    @endif
</div>

<div class="form-group">
    <label for="url">URL</label>
    <input type="text" id="url" name="url" class="form-control" value="{{ old('url', $link->url) }}" required>
    @if ($errors->has('url'))
        <small class="form-text text-muted">
            {{ $errors->first('url') }}
        </small>
    @endif
</div>

resources/views/links/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Links</h1>

        <div class="card">
            <div class="card-body">
                <div class="text-right" style="margin-bottom: 20px;">
                    <a href="{{ route('links.create') }}" class="btn btn-primary">
                        Add Link
                    </a>
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>URL</th>
                        <th>Link</th>
                        <th>Views</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse ($links as $link)
                        <tr>
                            <td>{{ $link->id }}</td>
                            <td>{{ $link->name }}</td>
                            <td>{{ $link->url }}</td>
                            <td>
                                <a href="{{ $link->link }}" target="_blank">
                                    {{ $link->link }}
                                </a>
                            </td>
                            <td>{{ $link->views }}</td>
                            <td>
                                <form action="{{ route('links.destroy', $link) }}" method="post">
                                    @method('DELETE')
                                    @csrf

                                    <button class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" align="center">
                                No links added.
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection